version: '3.4'

volumes:
  l1_data:
  kroma_log:

services:
  l1:
    pid: host # allow debugging
    image: ethereum/client-go:v1.10.22
    ports:
      - "8545:8545"
      - "8546:8546"
    environment:
      CHAIN_ID: 900
    volumes:
      - "l1_data:/db"
      - "${PWD}/entrypoint-l1.sh:/entrypoint.sh"
      - "${PWD}/genesis-l1.json:/genesis.json"
      - "${PWD}/jwt-secret.txt:/config/jwt-secret.txt"
    entrypoint:
      - "/bin/sh"
      - "/entrypoint.sh"
